baseurl = "https://glowing-fairy-06486d.netlify.app/" 
title = "CAS-IX"
theme = "hugo-universal-theme"
themesDir = "./themes"
languageCode = "en-us"
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

# number of words of summarized post content (default 70)
summaryLength = 35

# Define the number of posts per page
paginate = 10

# not pluralize title pages by default
pluralizelisttitles = false

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      linkifyProtocol = 'https'
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      autoHeadingID = true
      autoHeadingIDType = 'github'
      [markup.goldmark.parser.attribute]
        block = false
        title = true
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false

[menu]


# Main menu
[[menu.main]]
    name       = "Home"
    identifier = "menu.home"
    url        = "/"
    weight     = 1



#list more

[[menu.main]]
    name       = "learn more"
    identifier = "menu.more"
    url        = "/img/more.jpg"
    weight     = 5

[[menu.main]]
    name       = "Learn more"
    identifier = "section.more"
    url        = ""
    weight     = 1
    parent     = "menu.more"
    post       = 1

[[menu.main]]
    name       = "Information list"
    url        = "/more/"
    weight     = 1
    parent     = "section.more"

[[menu.main]]
    name       = "Network Peering"
    url        = "/more/Network-Peering/"
    weight     = 8
    parent     = "section.more"

[[menu.main]]
    name       = "CDN"
    url        = "/more/CDN"
    weight     = 3
    parent     = "section.more"

[[menu.main]]
    name       = "Cloud Provider"
    url        = "/more/cloud-provider"
    weight     = 4
    parent     = "section.more"

[[menu.main]]
    name       = "Financial sector"
    url        = "/more/financial-sector"
    weight     = 5
    parent     = "section.more"

[[menu.main]]
    name       = "High traffic websites"
    url        = "/more/traffic"
    weight     = 6
    parent     = "section.more"

[[menu.main]]
    name       = "Key accounts"
    url        = "/more/key-accounts"
    weight     = 7
    parent     = "section.more"

[[menu.main]]
    name       = "Transit ip and Peering"
    url        = "/more/transit-ip-peering"
    weight     = 2
    parent     = "section.more"



[[menu.main]]
    identifier = "contact"
    name       = "Contact"
    url        = "/contact/"
    weight     = 7



[[menu.main]]
    identifier = "services"
    name       = "services"
    url        = "/img/service3.png"
    weight     = 2

[[menu.main]]
    identifier = "section.services"
    name       = "services"
    url        = ""
    weight     = 1
    parent     = "services"
    post      = "1"

[[menu.main]]
    name       = "Internet peering"
    url        = "/services/peering/"
    weight     = 1
    parent     = "section.services"

[[menu.main]]
    name       = "private interconnect"
    url        = "/services/private/"
    weight     = 3
    parent     = "section.services"

[[menu.main]]
    name       = "Cloud connect"
    url        = "/services/cloud/"
    weight     = 2
    parent     = "section.services"

[[menu.main]]
    name       = "Easyaccess"
    url        = "/services/easyaccess/"
    weight     = 4
    parent     = "section.services"

[[menu.main]]
    name       = "Colocation"
    url        = "/services/colocation/"
    weight     = 5
    parent     = "section.services"


# Top bar social links menu

[[menu.topbar]]
    weight = 1
    name = "Phone"
    url = "tel:+12 34 567 89 01"
    pre = "<i class='fas fa-2x fa-phone'></i>"

[[menu.topbar]]
    weight = 2
    name = "GitHub"
    url = "https://github.com/devcows/hugo-universal-theme"
    pre = "<i class='fab fa-2x fa-github'></i>"

[[menu.topbar]]
    weight = 3
    name = "Facebook"
    url = "http://facebook.com"
    pre = "<i class='fab fa-2x fa-facebook'></i>"

[[menu.topbar]]
    weight = 4
    name = "Twitter"
    url = "http://twitter.com"
    pre = "<i class='fab fa-2x fa-twitter'></i>"

[[menu.topbar]]
    weight = 5
    name = "Email"
    url = "mailto:hello@universal.com"
    pre = "<i class='fas fa-2x fa-envelope'></i>"

[params]
    viewMorePostLink = "/more/"
    author = "N+ONE"
    mainSections = ["more"]
    defaultDescription = "CAS-IX website by N+ONE"

    # Social media
    facebook_site = "img/logo-casix.png" # the Facebook handle of your site ('https://www.facebook.com/HANDLE')
    twitter_site = "img/logo-casix.png" # the Twitter handle of your site (without the '@')
    default_sharing_image = "img/logo-casix.png"

    # Google Maps widget: If `googleMapsApiKey` is not set, no key will be passed to Google (which likely results in a broken map widget).
    enableGoogleMaps = false
    googleMapsApiKey = "AIzaSyAv7Sza8NSp9_l_g8G2vlo0H4ydEPn_2jY"

    latitude = "-12.043333"
    longitude = "-77.028333"

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "casix"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 50 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - register your account to https://formspree.io/register
    # - login and create new form
    # - set your form's endpoint url under 'formspree_action' below
    # - upload the generated site to your server
    # - test a dummy email yourself
    # - you're done. Happy mailing!
    #
    # Enable the contact form by entering your Formspree.io endpoint url
    formspree_action = "https://formspree.io/sample/of/endpoint"
    contact_form_ajax = false

    # Formspree form supports Google reCAPTCHA Key (type v2).
    # If you use this feature, you should enable reCAPTCHA feature in the Formspree dashboard.
    #
    # By default, Formspree use a redirect page for recaptcha widget.
    # If you use a recaptcha widget in your contact page, you should do next steps.
    # (if you don't want, skip these steps)
    #
    #   1. register your site on Google recaptcha admin page: https://www.google.com/recaptcha/admin
    #   2. select reCAPTCHA v2 and checkbox widget type.
    #   3. remember site key and secret key.
    #   4. enter secret key into "Custom reCAPTCHA Key" field in your Formspree form setting page.
    #   5. change `enableRecaptchaInContactForm` is to true
    #   6. enter site key into `googleRecaptchaKey` to enable a recaptcha widget in your page.
    #
    enableRecaptchaInContactForm = false
    googleRecaptchaKey = "site_key_for_google_recaptcha"

    about_us = "<p>A recognized leader in the colocation and online services industry for more than 10 years, N+ONE DATACENTERS helps customers deliver high-quality services and technology solutions.</p>"
    copyright = "Copyright (c) 2022, N+ONE DATACENTERS; all rights reserved."

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    dropdown_mouse_over = false

    disabled_logo = false
    logo_text = "CAS-IX"

    logo = "img/logo-casix.png"
    logo_small = "img/logo-casix.png"
    contact_url = "/contact"
    address = """<p class="text-uppercase"><strong>Universal Ltd.</strong>
        <br>13/25 New Avenue
        <br>Newtown upon River
        <br>45Y 73J
        <br>England
        <br>
        <strong>Great Britain</strong>
      </p>
      """

[permalinks]
    more = "/more/:filename/"
    services = "/services/:filename/"

# Enable or disable top bar with social icons
[params.topbar]
    enable = false
    text = """<p class="hidden-sm hidden-xs">Contact us on +420 777 555 333 or hello@universal.com.</p>
      <p class="hidden-md hidden-lg"><a href="tel:+420 777 555 333" data-animate-hover="pulse"><i class="fas fa-phone"></i></a>
      <a href="mailto:hello@universal.com" data-animate-hover="pulse"><i class="fas fa-envelope"></i></a>
      </p>
      """

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = false
    tags = false
    search = false

[params.carouselCustomers]
    items = 6
    auto_play = false
    slide_speed = 2000
    pagination_speed = 1000

[params.carouselTestimonials]
    items = 4
    auto_play = false
    slide_speed = 2000
    pagination_speed = 1000

[params.carouselHomepage]
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more information take a look at the README.
    enable = true
    auto_play = true
    slide_speed = 2000
    pagination_speed = 1000

[params.features]
    enable = true
    cols = 3 # Default: 3, Available values 2,3,4,6
    # All features are defined in their own files. You can find example items
    # at 'exampleSite/data/features'.
    # For more information take a look at the README.

[params.testimonials]
    enable = true
    # All testimonials are defined in their own files. You can find example items
    # at 'exampleSite/data/testimonials'.
    # For more information take a look at the README.
    title = "Testimonials"
    subtitle = "We have worked with many partners and we always like to hear they come out from the cooperation happy and satisfied. Have a look what our partners said about us."

[params.see_more]
    enable = true
    icon = "far fa-envelope"
    title = "Do you want to contact us?"
    subtitle = "Find below our contact page"
    link_url = "/contact"
    link_text = "Contact us"

[params.clients]
    enable = true
    # All clients are defined in their own files. You can find example items
    # at 'exampleSite/data/clients'.
    # For more information take a look at the README.
    title = "Leading Carriers & Peering Partners"
    subtitle = ""

[params.recent_posts]
    enable = true
    title = "Learn more"  
    #subtitle = "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo."
    hide_summary = false

[params.footer.recent_posts]
    enable = true

[taxonomies]
  category = "categories"
  tag = "tags"
  author = "authors"
